export LOCAL_PATH=~/local
export LOCAL_BIN="${LOCAL_PATH}/bin"

export EDITOR=${LOCAL_BIN}/gvim
export PATH=${LOCAL_BIN}:$PATH

PS1="\[\e[1;34m\]\u@\h\[\e[0m\] [ \W ] $ "

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
