source ~/GitHub/rkiel/git-utilities/dotfiles/bashrc
source ~/GitHub/rkiel/node-utilities/dotfiles/bashrc

[[ -s "$HOME/.rvm/scripts/rvm" ]] && export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

alias more='less -RX'
