export LOCAL_BIN="~/bin"

export EDITOR=${LOCAL_BIN}/gvim
export PATH=${LOCAL_BIN}:$PATH

source ~/.git-completion.bash
source ~/.git-prompt.sh

# PS1="\[\e[1;34m\]\u@\h\[\e[0m\] [ \W ] $ "

export PS1='[\[\e[0;35m\]\u@\h\[\e[0m\] \[\e[1;34m\]\W\[\e[0;32m\]$(__git_ps1 " %s")\[\e[0m\]]\$ '

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

if [ -f ~/.bashrc_local ]; then
  source ~/.bashrc_local
fi
