export LOCAL_BIN="~/bin"

export EDITOR=${LOCAL_BIN}/gvim
export PATH=${LOCAL_BIN}:$PATH

PS1="\[\e[1;34m\]\u@\h\[\e[0m\] [ \W ] $ "

source ~/.git-completion.bash

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
